source $VIMRUNTIME/vimrc_example.vim
source $VIMRUNTIME/mswin.vim
behave mswin

set diffexpr=MyDiff()
function MyDiff()
  let opt = '-a --binary '
  if &diffopt =~ 'icase' | let opt = opt . '-i ' | endif
  if &diffopt =~ 'iwhite' | let opt = opt . '-b ' | endif
  let arg1 = v:fname_in
  if arg1 =~ ' ' | let arg1 = '"' . arg1 . '"' | endif
  let arg2 = v:fname_new
  if arg2 =~ ' ' | let arg2 = '"' . arg2 . '"' | endif
  let arg3 = v:fname_out
  if arg3 =~ ' ' | let arg3 = '"' . arg3 . '"' | endif
  let eq = ''
  if $VIMRUNTIME =~ ' '
    if &sh =~ '\<cmd'
      let cmd = '""' . $VIMRUNTIME . '\diff"'
      let eq = '"'
    else
      let cmd = substitute($VIMRUNTIME, ' ', '" ', '') . '\diff"'
    endif
  else
    let cmd = $VIMRUNTIME . '\diff'
  endif
  silent execute '!' . cmd . ' ' . opt . arg1 . ' ' . arg2 . ' > ' . arg3 . eq
endfunction

"no vi-compatible
set nocompatible

"line sumbering
set nu

"syntax highlighting
syntax on

"color theme
colorscheme wombat256

"continuar lineas
set nowrap

"algunos mapeos utiles
map <F7> :prev
map <F8> :n
map <C-D> :q!
map <C-Q> :x!
map <C-S> :w

"cambiar ubicacion de los archivos de respaldo
set backupdir-=.
set backupdir^=$TEMP\vim

"indentacion
set softtabstop=4
"set shiftwidth=4

"encoding
set encoding=utf-8
set fileencoding=utf-8

"deshabilitar el resaltado de los resultado de una busqueda anterior
nnoremap <esc> :noh<return><esc>
